version: '3.8'
services:
  catalogdb:
    image: mongo:latest
  basketdb:
    image: redis:latest
  discountdb:
    image: postgres:latest
  identitydb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  rabbitmq:
    image: rabbitmq:3.10.7-management
volumes:
  catalogdb_volume:
  discount_volume:
  identitydb_volume:
  orderdb_volume:
